server:
  port: 8080

spring:
  application:
    name: source-knowledge
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/
      database: source-knowledge

logging:
  level:
    root: INFO